# fly.toml app configuration file generated for aether-backend on 2024-10-01T01:04:52-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aether-backend'
primary_region = 'qro'

[build]

[http_service]
  internal_port = 3030
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4
